### ISSUE TITLE
centerline of static map

### ISSUE THREAD

**Issue by ChevinB** [argoverse/av2-api#104]
I noticed that we have two methods to get the centerline of lane_segment.
First, we just get the data from raw map file.
Second, we can use the function of class ArgoverseStaticMap which is "get_lane_segment_centerline" to get the centerline. 
I wanna know the difference of these two methods.

**Comment by wqi** [comment]
Hi @ChevinB, apologies for the delayed response.

The easiest way to obtain lane segment centerlines would be to use the [`get_lane_segment_centerline`](https://github.com/argoverse/av2-api/blob/main/src/av2/map/map_api.py#L443) function, as you've correctly identified.

The JSON representation we use to serialize maps only stores the left and right lane boundaries, so that function helps us interpolate the centerline on-demand.

Hope that clears up any confusion! I'll close out the issue for the time being, but please feel free to re-open if you have any follow up questions! :-)
