### ISSUE TITLE
run [ run_generate_scenario_visualizations ] ,display ：TypeError: str expected, not int

### ISSUE THREAD

**Issue by betterqiang** [argoverse/av2-api#121]
**I found a super interesting mistake. As shown in the figure below,**
 **`run_generate_scenario_visualizations1`**  from **`run_generate_scenario_visualizations`** copy.
The **two functions are exactly the same**.
But here comes something interesting
------------------------------------------------------------------------------------------------------

I'm running  **`run_generate_scenario_visualizations`** ,will error ,   _TypeError: str expected, not int_
<img width="523" alt="截图_20230316192128" src="https://user-images.githubusercontent.com/122032889/225601924-6e8b5949-a8be-4bcc-ae8f-8e5b09cf619b.png">

But run   **`run_generate_scenario_visualizations1`** is ok.
______________________________________________________________________________
I guess it's caused by the following code, but I don't know why
@click.option("--debug", is_flag=True, default=False, help="Runs preprocessing in single-threaded mode when enabled.")
------------------------------------------------------------------------------------------------------------------

<img width="852" alt="截图_20230316191416" src="https://user-images.githubusercontent.com/122032889/225600336-de47bb4f-5edc-4820-b074-1f9a31c1b4b2.png">

**Comment by wqi** [comment]
Hi @betterqiang, the discrepancy you're seeing is likely due to the use of Click decorators and not related to the underlying AV2 functionality.

If you call `run_generate_scenario_visualizations` without using the Click entry point function, everything should work just fine. 

Going to close out this issue for the time being, but please feel free to re-open if you have further questions. :-)
